### ISSUE TITLE
Je API

### ISSUE THREAD

**Issue by wimmelstein** [Bombajofter/API-Java-Advanced#1]
Mats,

Ik heb naar je code gekeken. Ik gebruik graag issues in Gitlab/Github om commentaar te geven op je code.

Het ziet er fantastisch uit. Mooi en creatief, meerdere modellen. Prima. Een paar kleine dingen:

1. Namem van packages zijn altijd met kleine letters. Dat is conventie. Je ziet bij de native java libraries ook bijvoorbeeld: java.util.function...

2. Zoals ik het zie zijn types en roles 2 verschillende dingen. Waarom zie ik dan een method: getChampionByRole(String type)? Het lijkt een klein ding, maar in wat complexere applicaties kan hier ontzettend veel misgaan. Lees hiervoor ook het boek van Robert C. Martin, hoofstuk 2: Meaningful names.

Met vriendelijke groet,
Wim Wiltenburg

**Comment by Bombajofter** [comment]
Wim, 

Bedankt dat je even naar mijn code hebt gekeken.

W je zegt bij punt 2 klopt inderdaad. Ik had de methode zitten testen en het was eerst een zoeken naar type methode. Ik heb er uiteindelijk een zoeken naar role methode van gemaakt en ben vergeten de naam van de variabelen om te zetten naar rol. 

Ik zal de feedback verwerken in de opdrachten van volgende week!

Met vriendelijke groet, 
Mats Webbers
